// Code generated by protoc-gen-go. DO NOT EDIT.
// source: im/im.foo.proto

package im

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Foo struct {
	Id                           *int32   `protobuf:"varint,1,req,name=Id" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *Foo) Reset()         { *m = Foo{} }
func (m *Foo) String() string { return proto.CompactTextString(m) }
func (*Foo) ProtoMessage()    {}
func (*Foo) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_foo_f697924db7e3c801, []int{0}
}

var extRange_Foo = []proto.ExtensionRange{
	{Start: 100, End: 199},
}

func (*Foo) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Foo
}
func (m *Foo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Foo.Unmarshal(m, b)
}
func (m *Foo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Foo.Marshal(b, m, deterministic)
}
func (dst *Foo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Foo.Merge(dst, src)
}
func (m *Foo) XXX_Size() int {
	return xxx_messageInfo_Foo.Size(m)
}
func (m *Foo) XXX_DiscardUnknown() {
	xxx_messageInfo_Foo.DiscardUnknown(m)
}

var xxx_messageInfo_Foo proto.InternalMessageInfo

func (m *Foo) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type Info struct {
	// Types that are valid to be assigned to TestOneof:
	//	*Info_Name
	//	*Info_Marriage
	//	*Info_Address
	TestOneof            isInfo_TestOneof `protobuf_oneof:"test_oneof"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_foo_f697924db7e3c801, []int{1}
}
func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (dst *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(dst, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

type isInfo_TestOneof interface {
	isInfo_TestOneof()
}

type Info_Name struct {
	Name string `protobuf:"bytes,4,opt,name=Name,oneof"`
}
type Info_Marriage struct {
	Marriage bool `protobuf:"varint,5,opt,name=Marriage,oneof"`
}
type Info_Address struct {
	Address string `protobuf:"bytes,6,opt,name=Address,oneof"`
}

func (*Info_Name) isInfo_TestOneof()     {}
func (*Info_Marriage) isInfo_TestOneof() {}
func (*Info_Address) isInfo_TestOneof()  {}

func (m *Info) GetTestOneof() isInfo_TestOneof {
	if m != nil {
		return m.TestOneof
	}
	return nil
}

func (m *Info) GetName() string {
	if x, ok := m.GetTestOneof().(*Info_Name); ok {
		return x.Name
	}
	return ""
}

func (m *Info) GetMarriage() bool {
	if x, ok := m.GetTestOneof().(*Info_Marriage); ok {
		return x.Marriage
	}
	return false
}

func (m *Info) GetAddress() string {
	if x, ok := m.GetTestOneof().(*Info_Address); ok {
		return x.Address
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Info) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Info_OneofMarshaler, _Info_OneofUnmarshaler, _Info_OneofSizer, []interface{}{
		(*Info_Name)(nil),
		(*Info_Marriage)(nil),
		(*Info_Address)(nil),
	}
}

func _Info_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Info)
	// test_oneof
	switch x := m.TestOneof.(type) {
	case *Info_Name:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Name)
	case *Info_Marriage:
		t := uint64(0)
		if x.Marriage {
			t = 1
		}
		b.EncodeVarint(5<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *Info_Address:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Address)
	case nil:
	default:
		return fmt.Errorf("Info.TestOneof has unexpected type %T", x)
	}
	return nil
}

func _Info_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Info)
	switch tag {
	case 4: // test_oneof.Name
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.TestOneof = &Info_Name{x}
		return true, err
	case 5: // test_oneof.Marriage
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.TestOneof = &Info_Marriage{x != 0}
		return true, err
	case 6: // test_oneof.Address
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.TestOneof = &Info_Address{x}
		return true, err
	default:
		return false, nil
	}
}

func _Info_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Info)
	// test_oneof
	switch x := m.TestOneof.(type) {
	case *Info_Name:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Name)))
		n += len(x.Name)
	case *Info_Marriage:
		n += 1 // tag and wire
		n += 1
	case *Info_Address:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Address)))
		n += len(x.Address)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

var E_Name = &proto.ExtensionDesc{
	ExtendedType:  (*Foo)(nil),
	ExtensionType: (*string)(nil),
	Field:         100,
	Name:          "im.Name",
	Tag:           "bytes,100,opt,name=Name",
	Filename:      "im/im.foo.proto",
}

func init() {
	proto.RegisterType((*Foo)(nil), "im.Foo")
	proto.RegisterType((*Info)(nil), "im.Info")
	proto.RegisterExtension(E_Name)
}

func init() { proto.RegisterFile("im/im.foo.proto", fileDescriptor_im_foo_f697924db7e3c801) }

var fileDescriptor_im_foo_f697924db7e3c801 = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0xcc, 0xd5, 0xcf,
	0xcc, 0xd5, 0x4b, 0xcb, 0xcf, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xca, 0xcc, 0x55,
	0x92, 0xe1, 0x62, 0x76, 0xcb, 0xcf, 0x17, 0xe2, 0xe3, 0x62, 0xf2, 0x4c, 0x91, 0x60, 0x54, 0x60,
	0xd2, 0x60, 0x0d, 0x62, 0xf2, 0x4c, 0xd1, 0x62, 0xe5, 0x48, 0x11, 0x38, 0xc1, 0xa8, 0x94, 0xc2,
	0xc5, 0xe2, 0x99, 0x97, 0x96, 0x2f, 0x24, 0xc2, 0xc5, 0xe2, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0xa2,
	0xc0, 0xa8, 0xc1, 0xe9, 0xc1, 0x10, 0x04, 0xe6, 0x09, 0xc9, 0x70, 0x71, 0xf8, 0x26, 0x16, 0x15,
	0x65, 0x26, 0xa6, 0xa7, 0x4a, 0xb0, 0x2a, 0x30, 0x6a, 0x70, 0x78, 0x30, 0x04, 0xc1, 0x45, 0x84,
	0xa4, 0xb8, 0xd8, 0x1d, 0x53, 0x52, 0x8a, 0x52, 0x8b, 0x8b, 0x25, 0xd8, 0xa0, 0xda, 0x60, 0x02,
	0x4e, 0x3c, 0x5c, 0x5c, 0x25, 0xa9, 0xc5, 0x25, 0xf1, 0xf9, 0x79, 0xa9, 0xf9, 0x69, 0x56, 0xd2,
	0x10, 0xd3, 0x85, 0xd8, 0xf5, 0x32, 0x73, 0xf5, 0xdc, 0xf2, 0xf3, 0x25, 0x52, 0x40, 0xea, 0x21,
	0x96, 0x00, 0x02, 0x00, 0x00, 0xff, 0xff, 0x66, 0xf0, 0x49, 0xfa, 0xb6, 0x00, 0x00, 0x00,
}
