// Code generated by protoc-gen-go. DO NOT EDIT.
// source: im/im.hello.proto

package im

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FOO int32

const (
	FOO_X FOO = 17
)

var FOO_name = map[int32]string{
	17: "X",
}
var FOO_value = map[string]int32{
	"X": 17,
}

func (x FOO) Enum() *FOO {
	p := new(FOO)
	*p = x
	return p
}
func (x FOO) String() string {
	return proto.EnumName(FOO_name, int32(x))
}
func (x *FOO) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FOO_value, data, "FOO")
	if err != nil {
		return err
	}
	*x = FOO(value)
	return nil
}
func (FOO) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_im_hello_5d58d8b2828a6286, []int{0}
}

type HelloWorld struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Str                  *string  `protobuf:"bytes,2,req,name=str" json:"str,omitempty"`
	Opt                  *int32   `protobuf:"varint,3,opt,name=opt" json:"opt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloWorld) Reset()         { *m = HelloWorld{} }
func (m *HelloWorld) String() string { return proto.CompactTextString(m) }
func (*HelloWorld) ProtoMessage()    {}
func (*HelloWorld) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_hello_5d58d8b2828a6286, []int{0}
}
func (m *HelloWorld) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloWorld.Unmarshal(m, b)
}
func (m *HelloWorld) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloWorld.Marshal(b, m, deterministic)
}
func (dst *HelloWorld) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloWorld.Merge(dst, src)
}
func (m *HelloWorld) XXX_Size() int {
	return xxx_messageInfo_HelloWorld.Size(m)
}
func (m *HelloWorld) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloWorld.DiscardUnknown(m)
}

var xxx_messageInfo_HelloWorld proto.InternalMessageInfo

func (m *HelloWorld) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *HelloWorld) GetStr() string {
	if m != nil && m.Str != nil {
		return *m.Str
	}
	return ""
}

func (m *HelloWorld) GetOpt() int32 {
	if m != nil && m.Opt != nil {
		return *m.Opt
	}
	return 0
}

func init() {
	proto.RegisterType((*HelloWorld)(nil), "im.HelloWorld")
	proto.RegisterEnum("im.FOO", FOO_name, FOO_value)
}

func init() { proto.RegisterFile("im/im.hello.proto", fileDescriptor_im_hello_5d58d8b2828a6286) }

var fileDescriptor_im_hello_5d58d8b2828a6286 = []byte{
	// 118 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0xcc, 0xd5, 0xcf,
	0xcc, 0xd5, 0xcb, 0x48, 0xcd, 0xc9, 0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xca,
	0xcc, 0x55, 0x72, 0xe0, 0xe2, 0xf2, 0x00, 0x09, 0x85, 0xe7, 0x17, 0xe5, 0xa4, 0x08, 0xf1, 0x71,
	0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x69, 0xb0, 0x06, 0x31, 0x65, 0xa6, 0x08, 0x09, 0x70,
	0x31, 0x17, 0x97, 0x14, 0x49, 0x30, 0x29, 0x30, 0x69, 0x70, 0x06, 0x81, 0x98, 0x20, 0x91, 0xfc,
	0x82, 0x12, 0x09, 0x66, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x10, 0x53, 0x8b, 0x87, 0x8b, 0xd9, 0xcd,
	0xdf, 0x5f, 0x88, 0x95, 0x8b, 0x31, 0x42, 0x40, 0x10, 0x10, 0x00, 0x00, 0xff, 0xff, 0x48, 0xc7,
	0x7d, 0xac, 0x67, 0x00, 0x00, 0x00,
}
